### ISSUE TITLE
Language!

### ISSUE THREAD

**Issue by trn1ty** [Code-Bullet/RubiksCubeAI#7]
my mom caught me looking at this program and when she saw the f-word she grounded me from fortnite!!!!!1!!

1/10 would not recommend

**Comment by samualtnorman** [comment]
I think this is for the better

**Comment by rushiiMachine** [comment]
That's why you don't look at stuff like this when parents are spying on you

**Comment by AlgoRhythm-Technologies** [comment]
this is why code bullet should take language classes.

**Comment by AlgoRhythm-Technologies** [comment]
his language is very inappropriate. I would appreciate it if he would stop using the f word every thirty seconds on his videos on youtube

**Comment by rushiiMachine** [comment]
Then don't fucking watch youtubers that swear

**Comment by BlackDragon4229** [comment]
if you don't like his language you don't have to listen to it

**Comment by trn1ty** [comment]
I grew up
